src/Entity/Funcionario.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Funcionario
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string")
     */
    private $nome;
    /**
     *@ORM\Column(type="datetime")
     */
    private $dataDeNascimento;
    /**
     * @ORM\Column(type="datetime")
     */
    private $dataDeEntrada;

    /**
     * @ORM\ManyToOne(targetEntity="Projeto", inversedBy="funcionarios")
     */
    private $projeto;

    /**
     * @ORM\OneToMany(targetEntity="HoraLancada", mappedBy="funcionario")
     */
    private $horasLancadas;

    public function getTempoNaEmpresa()
    {
        $hoje = new \DateTime();
        $difetenca = $hoje->diff($this->dataDeEntrada);
        return  $difetenca;
    }
    public function getDataDeEntrada()
    {
        return $this->dataDeEntrada;
    }

    public function setDataDeEntrada($dataDeEntrada)
    {
        $this->dataDeEntrada = $dataDeEntrada;
        return $this;
    }

    public function getDataDeNascimento()
    {
        return $this->dataDeNascimento;
    }

    public function setDataDeNascimento($dataDeNascimento)
    {
        $this->dataDeNascimento = $dataDeNascimento;
        return $this;
    }

    public function getNome()
    {
        return $this->nome;
    }

    public function setNome($nome)
    {
        $this->nome = $nome;
        return $this;
    }
    public function getId()
    {
        return $this->id;
    }
    public function getProjeto()
    {
        return $this->projeto;
    }

    public function setProjeto($projeto)
    {
        $this->projeto = $projeto;
    }
    public function getHorasLancadas()
    {
        return $this->horasLancadas;
    }

    public function setHorasLancadas($horasLancadas)
    {
        $this->horasLancadas = $horasLancadas;
    }
}

src/Entity/HoraLancada.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class HoraLancada
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $descricao;

    /**
     * @ORM\Column(type="float")
     */
    private $quantidade;

    /**
     * @ORM\ManyToOne(targetEntity="Funcionario", inversedBy="horasLancadas")
     */
    private $funcionario;

    /**
     * @ORM\ManyToOne(targetEntity="Projeto", inversedBy="horasLancadas")
     */
    private $projeto;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getDescricao()
    {
        return $this->descricao;
    }

    public function setDescricao($descricao)
    {
        $this->descricao = $descricao;
    }

    public function getQuantidade()
    {
        return $this->quantidade;
    }

    public function setQuantidade($quantidade)
    {
        $this->quantidade = $quantidade;
    }

    public function getFuncionario()
    {
        return $this->funcionario;
    }

    public function setFuncionario($funcionario)
    {
        $this->funcionario = $funcionario;
    }

    public function getProjeto()
    {
        return $this->projeto;
    }

    public function setProjeto($projeto)
    {
        $this->projeto = $projeto;
    }
}

src/Entity/Projeto.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Projeto
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $nome;

    /**
     * @ORM\OneToMany(targetEntity="Funcionario", mappedBy="projeto")
     */
    private $funcionarios;

    /**
     * @ORM\OneToMany(targetEntity="HoraLancada", mappedBy="projeto")
     */
    private $horasLancadas;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getNome()
    {
        return $this->nome;
    }

    public function setNome($nome)
    {
        $this->nome = $nome;
    }

    public function getFuncionarios()
    {
        return $this->funcionarios;
    }

    public function setFuncionarios($funcionarios)
    {
        $this->funcionarios = $funcionarios;
    }


    public function getHorasLancadas()
    {
        return $this->horasLancadas;
    }

    public function setHorasLancadas($horasLancadas)
    {
        $this->horasLancadas = $horasLancadas;
    }
}

src/Controller/FuncionarioController.php
<?php

namespace App\Controller;

use App\Entity\Funcionario;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class FuncionarioController extends AbstractController
{
    /**
     * @Route("/funcionario/mostra/{id}")
     */
    public function mostraAction(Funcionario $funcionario)
    {

        return $this->render('Funcionario/mostra.html.twig', ["funcionario" => $funcionario]);
    }
    /**
     * @Route("/funcionario/novo",methods="GET")
     */
    public function formulario()
    {
        return $this->render("Funcionario/novo.html.twig");
    }
    /**
     * @Route("/funcionario/novo",methods="POST")
     */
    public function cria(Request $request)
    {
        $nome = $request->get("nome");
        $dataDeNascimento = $request->get("dataDeNascimento");
        $dataDeNascimento = new \DateTime($dataDeNascimento);
        $funcionario = new Funcionario();
        $funcionario->setNome($nome);
        $funcionario->setDataDeNascimento($dataDeNascimento);
        $funcionario->setDataDeEntrada(new \DateTime());

        $salvar = $this->getDoctrine()->getManager();
        $salvar->persist($funcionario);
        $salvar->flush();
        return $this->redirect("mostra/" . $funcionario->getId());
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function indexAction()
    {
        return $this->render('index.html.twig');
    }
}

templates/Funcionario/mostra.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            Funcionario
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <tr>
                        <th>Nome</th>
                        <td>{{ funcionario.nome }}</td>
                    </tr>
                    <tr>
                        <th>Data de Nascimento</th>
                        <td>{{ funcionario.dataDeNascimento|date("d-m-Y") }}</td>
                    </tr>
                    <tr>
                        <th>Data de entrada</th>
                        <td>{{ funcionario.dataDeEntrada|date("d-m-Y") }}</td>
                    </tr>
                    <tr>
                        <th>Tempo na empresa</th>
                        <td>{{ funcionario.tempoNaEmpresa|date("%Y anos, %m meses, %d dias") }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/Funcionario/novo.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Funcionário</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Novo
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <form role="form" action="/funcionario/novo" method="POST">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input class="form-control" name="nome" type="text"
                                           placeholder="Digite o nome do funcionario" required>
                                </div>
                                <div class="form-group">
                                    <label>Data de Nascimento</label>
                                    <input class="form-control" name="dataDeNascimento" required type="date">
                                </div>
                                <button type="submit" class="btn btn-default">Cirar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Tik Tok</title>
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Tik Tok</a>
        </div>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Busca...">
                            <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-briefcase fa-fw"></i> Funcionario<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="/funcionario/novo">Novo</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div id="page-wrapper">
            {% block body %}{% endblock %}
        </div>
    </nav>
</div>
<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="/vendor/metisMenu/metisMenu.min.js"></script>
<script src="/dist/js/sb-admin-2.js"></script>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>
        Bem vindo!
        {{ 'now'|date('Y/m/d h:i') }}
    </h1>
{% endblock %}